# Generated by Django 2.1.5 on 2019-02-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20190218_0613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', '-exam_grade']},
        ),
    ]
